//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GYEntities : DbContext
    {
        public GYEntities()
            : base("name=GYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Active> Active { get; set; }
        public virtual DbSet<AdminInfo> AdminInfo { get; set; }
        public virtual DbSet<Collect> Collect { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Festive> Festive { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<MoviesType> MoviesType { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<ReComment> ReComment { get; set; }
        public virtual DbSet<ReMessage> ReMessage { get; set; }
        public virtual DbSet<Theme> Theme { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
